export const SET_IS_LOADING = "SET_IS_LOADING";
export const GET_COUNTRY_DATA = "GET_COUNTRY_DATA";
export const GET_HISTORICAL_DATA = "GET_HISTORICAL_DATA";
export const GET_COUNTRIES = "GET_COUNTRIES";
