export const SET_IS_LOADING = "SET_IS_LOADING";
export const GET_COUNTRY_DATA = "GET_COUNTRY_DATA";
export const GET_HISTORICAL_DATA = "GET_HISTORICAL_DATA";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_TOP_AFFECTED_COUNTRIES = "GET_TOP_AFFECTED_COUNTRIES";
export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";

// Error related actions
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
